INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy Tactics', 'RPG', 1997, 2270000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Silent Hill', 'Survival Horror', 1999, 2000000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Yu-Gi-Oh! Forbidden Memories', 'Card Game', 1999, 2510804, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Gran Turismo', 'Corrida', 1997, 10850000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Gran Turismo 2', 'Corrida', 1999, 9370000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy VII', 'RPG', 1997, 10022228, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy VIII', 'RPG', 1999, 8600000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Tekken 3', 'Luta', 1998, 8300000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Crash Bandicoot', 'Plataforma',1996, 6820000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Crash Bandicoot 2: Cortex Strikes Back', 'Plataforma', 1997, 7580000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Crash Bandicoot: Warped', 'Plataforma', 1998, 7130000, 1);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Resident Evil', 'Survival Horror', 1996, 5080000, 1);

INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Kingdom Hearts', 'RPG', 2002, 5900000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Resident Evil 4', 'Ação', 2005, 2300000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Grand Theft Auto III', 'Ação', 2001, 8305000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Grand Theft Auto: Vice City', 'Ação', 2002, 10500000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Grand Theft Auto: San Andreas', 'Ação', 2004, 17330000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Gran Turismo 3: A-Spec', 'Corrida', 2001, 14890000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Gran Turismo 4', 'Corrida', 2004, 11760000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy X', 'RPG', 2001, 8500000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy XII', 'RPG', 2006, 6000000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Tekken 5', 'Luta', 2005, 6000000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('God of War', 'Ação', 2005, 4610000, 2);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('God of War II', 'Ação', 2007, 4240000, 2);

INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Castlevania: Portrait of Ruin', 'Metroidvania', 2006, 400000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Castlevania: Order of Ecclesia', 'Metroidvania', 2008, 370000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('New Super Mario Bros', 'Plataforma', 2006, 30800000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon Diamond and Pearl', 'RPG', 2006, 17670000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon Black and White', 'RPG', 2010, 15640000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon Platinum Version', 'RPG', 2008, 7060000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Mario 64 DS', 'Plataforma', 2004, 11060000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mario & Luigi: Bowsers Inside Story', 'RPG', 2009, 4560000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mario Kart Ds', 'Corrida', 2005, 23600000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('The Legend of Zelda: Phantom Hourglass', 'Ação e Aventura', 2007, 4760000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('The Legend of Zelda: Spirit Tracks', 'Ação e Aventura', 2009, 2960000, 3);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy Tactics Advance 2: Grimoire of The Rift', 'RPG', 2007, 670000, 3);

INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Metroid', 'Ação e Aventura', 1994, 1420000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Mario World', 'Plataforma', 1990, 20610000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Donkey Kong Country', 'Plataforma', 1994, 9300000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Mario Kart', 'Corrida', 1992, 8760000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Street Fighter II: The World Warrior', 'Luta', 1992, 6300000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Donkey Kong Country 2: Diddys Kong Quest', 'Plataforma', 1995, 5150000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('The Legend of Zelda: A Link to the Past', 'Ação e Aventura', 1991, 4610000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Mario World 2: Yoshis Island', 'Plataforma', 1995, 4120000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy VI', 'RPG', 1994, 3420000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('F-Zero', 'Corrida', 1990, 2850000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Dragon Quest VI', 'RPG', 1995, 3200000, 4);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mega Man X', 'Plataforma', 1993, 1160000, 4);

INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon Emerald Version', 'RPG', 2004, 7060000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon Ruby and Sapphire', 'RPG', 2002, 16220000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon FireRed and LeafGreen', 'RPG', 2004, 12000000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Metroid Fusion', 'Ação e Aventura', 2002, 1600000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Yu-Gi-Oh! The Eternal Duelist Soul', 'Card Game', 2001, 1710534, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mario Kart: Super Circuit', 'Corrida', 2001, 5910000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Mario World: Super Mario Advance 2', 'Plataforma', 2001, 5690000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Final Fantasy Tactics Advance', 'RPG', 2003, 1621000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Wario Land 4', 'Plataforma', 2001, 2200000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mario vs. Donkey Kong', 'Plataforma', 2004, 1370000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('F-Zero: Maximum Velocity', 'Corrida', 2001, 1050000, 5);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('The Legend of Zelda: The Minish Cap', 'Ação e Aventura', 2004, 1760000, 5);

INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mario Kart 7', 'Corrida', 2011, 18980000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Bravely Default', 'RPG', 2012, 1400000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Super Mario 3D Land ', 'Plataforma', 2011, 12880000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Yo-kai Watch 2', 'RPG', 2014, 7300000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Luigis Mansion: Dark Moon', 'Ação e Aventura', 2013, 6480000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('The Legend of Zelda: A Link Between Worlds', 'Ação e Aventura', 2013, 4260000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Fire Emblem Awakening', 'Tactical RPG', 2012, 2370000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Fire Emblem Fates: Birthright and Conquest', 'Tactical RPG', 2015, 3090000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Fire Emblem Echoes: Shadows of Valentia', 'Tactical RPG', 2017, 1000000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Mario & Luigi: Dream Team', 'RPG', 2013, 2700000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon X and Y', 'RPG', 2013, 16720000, 6);
INSERT INTO tb_game (game_name, game_genre, release_year, units_sold, game_console_id) values('Pokémon Sun and Moon', 'RPG', 2016, 16320000, 6);